# virtual_candle_simulator.py
# Display all candles at once with fixed Y-axis
# Android / Pydroid friendly
# Comments are in English

import matplotlib.pyplot as plt
import csv

# ========================
# Configurable parameters
# ========================
input_file = 'generated_candles.csv'  # CSV file generated by candle_generator.py
margin = 1                            # extra margin for price axis

# ========================
# Read CSV
# ========================
candles = []

with open(input_file, 'r') as f:
    reader = csv.DictReader(f)
    for row in reader:
        candles.append({
            'timestamp': row['timestamp'],
            'open': float(row['open']),
            'high': float(row['high']),
            'low': float(row['low']),
            'close': float(row['close']),
            'volume': int(row['volume']),
            'spread': float(row['spread'])
        })

# ========================
# Determine global min/max for fixed Y-axis
# ========================
global_low = min(c['low'] for c in candles)
global_high = max(c['high'] for c in candles)

# ========================
# Plot all candles at once
# ========================
fig, ax = plt.subplots()

ax.set_ylim(global_low - margin, global_high + margin)

for i, c in enumerate(candles):
    color = 'green' if c['close'] >= c['open'] else 'red'
    # draw high-low line
    ax.plot([i, i], [c['low'], c['high']], color='black')
    # draw open-close rectangle
    ax.bar(i, c['close']-c['open'], bottom=c['open'], width=0.5, color=color)

ax.set_xticks(range(len(candles)))
ax.set_xticklabels([c['timestamp'].split(' ')[1] for c in candles], rotation=45)
ax.set_ylabel('Price')
ax.set_title('Virtual Candlestick Simulator (Static Display)')

plt.show()